// let message=[
//     "hey,how's it going",
//     "i'm great",
//     "all good"
// ]
// let newmessage="same hear"

// message.push(newmessage)

// console.log(message)
// message.pop(newmessage)
// console.log(message)

// let randomNumber=Math.random()*6
// let floorNumber=Math.floor(3.45675)
// let randomNumber1=Math.floor(Math.random()*6)
// let randomNumber2=Math.ceil(Math.random()*6)
// console.log(floorNumber)
// console.log(randomNumber)
// console.log(randomNumber1)
// console.log(randomNumber2)

let hasSolvedChalleneg=false
let hashintsleft=false
if(hasSolvedChalleneg==false && hashintsleft==false)
{
    showSolution()
}
function showSolution()
{
    console.log("showing the solution...")
}
 
